# fly.toml app configuration file generated for truffleruby-jfr-demo on 2026-01-17T23:42:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'truffleruby-jfr-demo'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
